"""create monitored services

Revision ID: 9eb88bbbefe4
Revises: 
Create Date: 2026-08-13 01:00:13.936668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb88bbbefe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('recovery_timeout', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='circuitstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitored_services')
    # ### end Alembic commands ###
